<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\C_flip.jpg" />
    <AvaloniaResource Remove="Assets\H %287%29.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Assets\C_flip.jpg" />
    <Content Remove="Assets\C_flip.jpg" />
    <Content Remove="Assets\H %287%29.jpg" />
    <Content Remove="Assets\H %287%29.jpg" />
    <Content Remove="Assets\HandSignH.jpg" />
    <Content Remove="Assets\HandSignV.jpg" />
    <Content Remove="Assets\HandsignW.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.1" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
	  <PackageReference Include="FluentAvaloniaUI" Version="2.2.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageReference Include="Emgu.CV" Version="4.10.0.5680" />
    <PackageReference Include="Emgu.CV.Bitmap" Version="4.10.0.5680" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.10.0.5680" />
    
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250401001" />
    <PackageReference Include="ReactiveUI" Version="20.3.1" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
	  
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\CameraView.axaml.cs">
      <DependentUpon>CameraView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
